[project]
name = "home-ops-toolbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ansible>=13.2.0",
    "github3-py>=4.0.1",
]
