- name: Ensure apt cache is up to date
  apt:
    cache_valid_time: 3600
    update_cache: yes

- name: Install packages
  apt:
    name:
      - syncthing
      - wireguard
      - cryptsetup
      - sshfs
      - vlc
      - htop
      - zsh
      - zsh-autosuggestions
    state: latest
