- name: Ensure apt cache is up to date
  apt:
    cache_valid_time: 3600
    update_cache: yes

- name: Install Syncthing and WireGuard
  apt:
    name:
      - syncthing
      - wireguard
    state: latest
