volumes:
  - name: cryptone
    uuid: 5fb8102d-6c30-4e85-90b9-5d48a52d5712
    maddkey: /home/me/.ssh/maddkey_whimsical-march-stipend
  - name: crypttwo
    uuid: 0280d4ec-c6d9-46c5-8feb-993c8c65c245
    maddkey: /home/me/.ssh/maddkey_reshuffle-cartoon-reenact
